# Generated by Django 4.1.5 on 2023-01-19 09:13

from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bouquet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Введите название', max_length=255, verbose_name='Название')),
                ('image', models.ImageField(upload_to='media', verbose_name='Изображение')),
                ('price', models.IntegerField(verbose_name='Стоимость')),
                ('bouquet_meaning', models.CharField(max_length=255, verbose_name='Описание')),
                ('floral_composition', models.CharField(max_length=255, verbose_name='Цветочная композиция')),
                ('status', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Введите категорию', max_length=255, verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=255, verbose_name='Адрес')),
                ('delivery_date', models.DateField(verbose_name='Дата доставки')),
                ('delivery_time', models.TimeField(verbose_name='Время доставки')),
                ('bouquet', models.ManyToManyField(blank=True, related_name='bouquets', to='bot.bouquet')),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Имя')),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(blank=True, db_index=True, max_length=128, null=True, region='RU', verbose_name='Номер покупателя')),
                ('orders', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Orders', to='bot.order', verbose_name='Заказы')),
            ],
        ),
        migrations.AddField(
            model_name='bouquet',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bot.category', verbose_name='Категория'),
        ),
    ]
