# Generated by Django 4.1.5 on 2023-01-18 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='bouquet',
            field=models.ManyToManyField(blank=True, related_name='bouquets', to='bot.bouquet'),
        ),
    ]
