# Generated by Django 4.1.5 on 2023-01-18 14:48

from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0002_alter_customer_orders'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
            ],
        ),
        migrations.RemoveField(
            model_name='bouquet',
            name='floral_composition',
        ),
        migrations.RemoveField(
            model_name='bouquet',
            name='phone_number',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='address',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='bouquet',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='delivery_date',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='delivery_time',
        ),
        migrations.AddField(
            model_name='customer',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, db_index=True, max_length=128, null=True, region='RU', verbose_name='Номер покупателя'),
        ),
        migrations.AlterField(
            model_name='bouquet',
            name='bouquet_meaning',
            field=models.CharField(max_length=255, verbose_name='Описание'),
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=255, verbose_name='Адрес')),
                ('delivery_date', models.DateField(verbose_name='Дата доставки')),
                ('delivery_time', models.TimeField(verbose_name='Время доставки')),
                ('bouquet', models.ManyToManyField(blank=True, related_name='bouquets', to='bot.bouquet')),
            ],
        ),
        migrations.AddField(
            model_name='bouquet',
            name='category',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='bot.category', verbose_name='Категория'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customer',
            name='orders',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='Orders', to='bot.order', verbose_name='Заказы'),
            preserve_default=False,
        ),
    ]
