# Generated by Django 4.1.5 on 2023-01-21 12:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0002_alter_customer_orders'),
    ]

    operations = [
        migrations.CreateModel(
            name='Flower',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Введите название цветов', max_length=255, verbose_name='Цветы')),
            ],
            options={
                'verbose_name': 'Цветы',
                'verbose_name_plural': 'Цветы',
            },
        ),
        migrations.AlterModelOptions(
            name='bouquet',
            options={'verbose_name': 'Букет', 'verbose_name_plural': 'Букеты'},
        ),
        migrations.AlterModelOptions(
            name='customer',
            options={'verbose_name': 'Покупатель', 'verbose_name_plural': 'Покупатели'},
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name': 'Заказ', 'verbose_name_plural': 'Заказы'},
        ),
        migrations.RemoveField(
            model_name='bouquet',
            name='floral_composition',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='orders',
        ),
        migrations.AddField(
            model_name='order',
            name='customer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='bot.customer', verbose_name='Покупатель'),
        ),
        migrations.RemoveField(
            model_name='order',
            name='bouquet',
        ),
        migrations.AddField(
            model_name='bouquet',
            name='flowers',
            field=models.ManyToManyField(related_name='flowers', to='bot.flower', verbose_name='Цветы в композиции'),
        ),
        migrations.AddField(
            model_name='order',
            name='bouquet',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='bot.bouquet', verbose_name='Букет'),
        ),
    ]
