# Generated by Django 4.1.5 on 2023-01-19 10:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0003_category_remove_bouquet_floral_composition_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bouquet',
            options={'verbose_name': 'Букет', 'verbose_name_plural': 'Букеты'},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Категория', 'verbose_name_plural': 'Категории'},
        ),
        migrations.AlterModelOptions(
            name='customer',
            options={'verbose_name': 'Покупатель', 'verbose_name_plural': 'Покупатели'},
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name': 'Заказ', 'verbose_name_plural': 'Заказы'},
        ),
        migrations.AlterField(
            model_name='bouquet',
            name='image',
            field=models.ImageField(upload_to='media', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='bouquet',
            name='title',
            field=models.CharField(help_text='Введите название', max_length=255, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='category',
            name='title',
            field=models.CharField(help_text='Введите категорию', max_length=255, verbose_name='Категория'),
        ),
        migrations.RemoveField(
            model_name='order',
            name='bouquet',
        ),
        migrations.AddField(
            model_name='order',
            name='bouquet',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='bot.bouquet', verbose_name='Букет>'),
            preserve_default=False,
        ),
    ]
